//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.Help {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceInfo() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.Help.ServiceInfo", typeof(ServiceInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 We have a huge collection of items. Anything you like, just &quot;Add to Cart&quot; Buy them all at once, then use quick purchase way to save you time. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_AddShoppingCartDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_AddShoppingCartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can easily sign up as our member with your Facebook account or mobile number. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_AddSiteMembership {
            get {
                return ResourceManager.GetString("Pages_ServicePage_AddSiteMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Everything at a glance 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_AtGlance {
            get {
                return ResourceManager.GetString("Pages_ServicePage_AtGlance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buy Them All at Once 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_BuyOnceAll {
            get {
                return ResourceManager.GetString("Pages_ServicePage_BuyOnceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every piece of information you write when you order something will be recorded in &quot;Address Book&quot;, so the next time you order you can simply choose the address you want from &quot;Address Book&quot;.You can edit and delete &quot;Address Book&quot; any time. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_CommonAddresseeDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_CommonAddresseeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy sign up 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_EasyJoin {
            get {
                return ResourceManager.GetString("Pages_ServicePage_EasyJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy to record 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_EasyRecord {
            get {
                return ResourceManager.GetString("Pages_ServicePage_EasyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quick Purchase 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_FastPay {
            get {
                return ResourceManager.GetString("Pages_ServicePage_FastPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 During the payment procedure, when you&apos;re writing information, simply check the box that says &quot;Save the payment and recipient information, and set it as quick purchase,&quot; to start using quick purchase. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_FillInformationDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_FillInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can see your order status,member qualification,and FAQ clearly in your account. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_GoodHelperDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_GoodHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy Buy 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_GoodLookingGoodBuy {
            get {
                return ResourceManager.GetString("Pages_ServicePage_GoodLookingGoodBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Easy Pay 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_MultiplePayment {
            get {
                return ResourceManager.GetString("Pages_ServicePage_MultiplePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Account 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_MyAccount {
            get {
                return ResourceManager.GetString("Pages_ServicePage_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 91mai just buy 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_NineYiWillBuy {
            get {
                return ResourceManager.GetString("Pages_ServicePage_NineYiWillBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add to shopping cart 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_PutShoppingCart {
            get {
                return ResourceManager.GetString("Pages_ServicePage_PutShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We provide an easy way to use search engine, just enter the item or keyword and you&apos;ll find it right away! 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_SearchKeyWordDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_SearchKeyWordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service description 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_ServiceDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We provide easy online payment methods. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_SiteProvidesPaymentMethods {
            get {
                return ResourceManager.GetString("Pages_ServicePage_SiteProvidesPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To ensure the safety of online shopping, you understand that we are going to verify this purchase with the credit card bank and the cardholder. Reminder, identity theft is illegal and will be prosecuted if found. 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_TransactionSecurityDescription {
            get {
                return ResourceManager.GetString("Pages_ServicePage_TransactionSecurityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simple way to sign up 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_WillJoin {
            get {
                return ResourceManager.GetString("Pages_ServicePage_WillJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Useful search tips 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_WillQuery {
            get {
                return ResourceManager.GetString("Pages_ServicePage_WillQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The best buying experience 的當地語系化字串。
        /// </summary>
        public static string Pages_ServicePage_WillToBuy {
            get {
                return ResourceManager.GetString("Pages_ServicePage_WillToBuy", resourceCulture);
            }
        }
    }
}
