//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.Components {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Desktop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Desktop() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.Components.Desktop", typeof(Desktop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About Us 的當地語系化字串。
        /// </summary>
        public static string Components_AboutUs {
            get {
                return ResourceManager.GetString("Components_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All promotions 的當地語系化字串。
        /// </summary>
        public static string Components_Activity_All {
            get {
                return ResourceManager.GetString("Components_Activity_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More promotions 的當地語系化字串。
        /// </summary>
        public static string Components_Activity_More {
            get {
                return ResourceManager.GetString("Components_Activity_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Latest promotions 的當地語系化字串。
        /// </summary>
        public static string Components_Activity_New {
            get {
                return ResourceManager.GetString("Components_Activity_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discount promotions 的當地語系化字串。
        /// </summary>
        public static string Components_Activity_Promotion {
            get {
                return ResourceManager.GetString("Components_Activity_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Brand Story 的當地語系化字串。
        /// </summary>
        public static string Components_BrandStory {
            get {
                return ResourceManager.GetString("Components_BrandStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More coupons 的當地語系化字串。
        /// </summary>
        public static string Components_Coupon_More {
            get {
                return ResourceManager.GetString("Components_Coupon_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More store discounts 的當地語系化字串。
        /// </summary>
        public static string Components_Coupon_MoreShop {
            get {
                return ResourceManager.GetString("Components_Coupon_MoreShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store discounts 的當地語系化字串。
        /// </summary>
        public static string Components_CouponShop {
            get {
                return ResourceManager.GetString("Components_CouponShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        public static string Components_Download {
            get {
                return ResourceManager.GetString("Components_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scan QR code to download 的當地語系化字串。
        /// </summary>
        public static string Components_DownloadApp {
            get {
                return ResourceManager.GetString("Components_DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon 的當地語系化字串。
        /// </summary>
        public static string Components_Ecoupon {
            get {
                return ResourceManager.GetString("Components_Ecoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More coupons 的當地語系化字串。
        /// </summary>
        public static string Components_Ecoupon_More {
            get {
                return ResourceManager.GetString("Components_Ecoupon_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extension 的當地語系化字串。
        /// </summary>
        public static string Components_Extension {
            get {
                return ResourceManager.GetString("Components_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gifts 的當地語系化字串。
        /// </summary>
        public static string Components_Gift {
            get {
                return ResourceManager.GetString("Components_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your mobile number 的當地語系化字串。
        /// </summary>
        public static string Components_InputMobileNumber {
            get {
                return ResourceManager.GetString("Components_InputMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log in/ Sign up 的當地語系化字串。
        /// </summary>
        public static string Components_Member_Login {
            get {
                return ResourceManager.GetString("Components_Member_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log Out 的當地語系化字串。
        /// </summary>
        public static string Components_Member_Logout {
            get {
                return ResourceManager.GetString("Components_Member_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Membership 的當地語系化字串。
        /// </summary>
        public static string Components_Member_Only {
            get {
                return ResourceManager.GetString("Components_Member_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Membership Terms 的當地語系化字串。
        /// </summary>
        public static string Components_Member_Statement {
            get {
                return ResourceManager.GetString("Components_Member_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid mobile number 的當地語系化字串。
        /// </summary>
        public static string Components_MobileFomat_Error {
            get {
                return ResourceManager.GetString("Components_MobileFomat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment Method 的當地語系化字串。
        /// </summary>
        public static string Components_Mode_Pay {
            get {
                return ResourceManager.GetString("Components_Mode_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund Method 的當地語系化字串。
        /// </summary>
        public static string Components_Mode_Returns {
            get {
                return ResourceManager.GetString("Components_Mode_Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping Method 的當地語系化字串。
        /// </summary>
        public static string Components_Mode_Transport {
            get {
                return ResourceManager.GetString("Components_Mode_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More 的當地語系化字串。
        /// </summary>
        public static string Components_More {
            get {
                return ResourceManager.GetString("Components_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Account 的當地語系化字串。
        /// </summary>
        public static string Components_MyAccount {
            get {
                return ResourceManager.GetString("Components_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Wishlist 的當地語系化字串。
        /// </summary>
        public static string Components_MyCollect {
            get {
                return ResourceManager.GetString("Components_MyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My coupons 的當地語系化字串。
        /// </summary>
        public static string Components_MyEcoupon {
            get {
                return ResourceManager.GetString("Components_MyEcoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Latest 的當地語系化字串。
        /// </summary>
        public static string Components_New {
            get {
                return ResourceManager.GetString("Components_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Latest added items 的當地語系化字串。
        /// </summary>
        public static string Components_New_AddItem {
            get {
                return ResourceManager.GetString("Components_New_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App 的當地語系化字串。
        /// </summary>
        public static string Components_OfficialApp {
            get {
                return ResourceManager.GetString("Components_OfficialApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter your mobile number and download the official app to have an even better shopping experience 的當地語系化字串。
        /// </summary>
        public static string Components_OfficialApp_Download {
            get {
                return ResourceManager.GetString("Components_OfficialApp_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use the official app right away 的當地語系化字串。
        /// </summary>
        public static string Components_OfficialApp_Use {
            get {
                return ResourceManager.GetString("Components_OfficialApp_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Orders 的當地語系化字串。
        /// </summary>
        public static string Components_OrderSearch {
            get {
                return ResourceManager.GetString("Components_OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checkout 的當地語系化字串。
        /// </summary>
        public static string Components_Pay {
            get {
                return ResourceManager.GetString("Components_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy Policy 的當地語系化字串。
        /// </summary>
        public static string Components_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Components_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        public static string Components_Product_Category {
            get {
                return ResourceManager.GetString("Components_Product_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Wishlist 的當地語系化字串。
        /// </summary>
        public static string Components_Product_Collect {
            get {
                return ResourceManager.GetString("Components_Product_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item image 的當地語系化字串。
        /// </summary>
        public static string Components_Product_Image {
            get {
                return ResourceManager.GetString("Components_Product_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discount 的當地語系化字串。
        /// </summary>
        public static string Components_Promotion {
            get {
                return ResourceManager.GetString("Components_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} discount promotions in total 的當地語系化字串。
        /// </summary>
        public static string Components_Promotion_Count {
            get {
                return ResourceManager.GetString("Components_Promotion_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discount + gift 的當地語系化字串。
        /// </summary>
        public static string Components_Promotion_Gift {
            get {
                return ResourceManager.GetString("Components_Promotion_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More discount promotions 的當地語系化字串。
        /// </summary>
        public static string Components_Promotion_More {
            get {
                return ResourceManager.GetString("Components_Promotion_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Countdown 的當地語系化字串。
        /// </summary>
        public static string Components_Reciprocal {
            get {
                return ResourceManager.GetString("Components_Reciprocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recommended items 的當地語系化字串。
        /// </summary>
        public static string Components_Recommend_Product {
            get {
                return ResourceManager.GetString("Components_Recommend_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item page image 的當地語系化字串。
        /// </summary>
        public static string Components_SalePage {
            get {
                return ResourceManager.GetString("Components_SalePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Top ranking 的當地語系化字串。
        /// </summary>
        public static string Components_SaleRank {
            get {
                return ResourceManager.GetString("Components_SaleRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send message 的當地語系化字串。
        /// </summary>
        public static string Components_Send_Message {
            get {
                return ResourceManager.GetString("Components_Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact Us 的當地語系化字串。
        /// </summary>
        public static string Components_Service_Information {
            get {
                return ResourceManager.GetString("Components_Service_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send Message 的當地語系化字串。
        /// </summary>
        public static string Components_Service_Message {
            get {
                return ResourceManager.GetString("Components_Service_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer service number 的當地語系化字串。
        /// </summary>
        public static string Components_Service_Phone {
            get {
                return ResourceManager.GetString("Components_Service_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FAQ 的當地語系化字串。
        /// </summary>
        public static string Components_Service_Question {
            get {
                return ResourceManager.GetString("Components_Service_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About Shop 的當地語系化字串。
        /// </summary>
        public static string Components_ShopIntroduction {
            get {
                return ResourceManager.GetString("Components_ShopIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cart 的當地語系化字串。
        /// </summary>
        public static string Components_ShoppingCart {
            get {
                return ResourceManager.GetString("Components_ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your shopping cart is empty 的當地語系化字串。
        /// </summary>
        public static string Components_ShoppingCartNoProduct {
            get {
                return ResourceManager.GetString("Components_ShoppingCartNoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer Service 的當地語系化字串。
        /// </summary>
        public static string Components_ShoppingDescription {
            get {
                return ResourceManager.GetString("Components_ShoppingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This website is best viewed in Google Chrome, Firefox, or IE10 or above 的當地語系化字串。
        /// </summary>
        public static string Components_Site_BestBrowser {
            get {
                return ResourceManager.GetString("Components_Site_BestBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Website main menu 的當地語系化字串。
        /// </summary>
        public static string Components_Site_Menu {
            get {
                return ResourceManager.GetString("Components_Site_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Website sub-menu 的當地語系化字串。
        /// </summary>
        public static string Components_Site_SecMenu {
            get {
                return ResourceManager.GetString("Components_Site_SecMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully added 的當地語系化字串。
        /// </summary>
        public static string Components_Success_Add {
            get {
                return ResourceManager.GetString("Components_Success_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removal successful 的當地語系化字串。
        /// </summary>
        public static string Components_Success_Remove {
            get {
                return ResourceManager.GetString("Components_Success_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Theme album 的當地語系化字串。
        /// </summary>
        public static string Components_Theme_Album {
            get {
                return ResourceManager.GetString("Components_Theme_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send download link 的當地語系化字串。
        /// </summary>
        public static string Components_TransferPoint {
            get {
                return ResourceManager.GetString("Components_TransferPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send download link to your phone for free 的當地語系化字串。
        /// </summary>
        public static string Components_TransferPoint_Free {
            get {
                return ResourceManager.GetString("Components_TransferPoint_Free", resourceCulture);
            }
        }
    }
}
