//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.ReturnGoodsRequest {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class List {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.ReturnGoodsRequest.List", typeof(List).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account No. 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_AccountNo {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The length is {0} characters, you have entered {1} characters, only numbers allowed 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_AccountNoMsgVerifi {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_AccountNoMsgVerifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter the correct account 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_AccountNoWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_AccountNoWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your return has been requested 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Applied {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return to order search 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Back {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account Name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankAccountOwner {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankAccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter account name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankAccountOwnerWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankAccountOwnerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bank Name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankName {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose bank name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankNameWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankSubName {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_BankSubNameWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_BankSubNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the correct mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_CellPhoneVerifi {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_CellPhoneVerifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please fill in the correct mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_CellPhoneWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_CellPhoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exchange 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ChangeGoods {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ChangeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Contact {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please fill in the correct recipient name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ContactWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ContactWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card bank 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_CreditCardBankName {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_CreditCardBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please describe the reason of return (200 words limit) 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_DescriptionMsg {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_DescriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taiwan address only, please don&apos;t write PO box 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_DistrictMsg {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_DistrictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address is required 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_DistrictRequired {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_DistrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address has to be 5 or more Chinese characters, letters or numbers 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_DistrictVerifi {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_DistrictVerifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area is required 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_DistrictWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_DistrictWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 please enter your account 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_EnterAccount {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter code or keyword 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_EnterKeyWord {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_EnterKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill in your Chinese full name 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_EnterName {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check {0} items you want 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_EnterProduct {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_EnterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose a reason 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_EnterReason {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_EnterReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gift with purchase 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Gift {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No item to return at the moment 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_NoData {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pickup information 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_PickupInfo {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_PickupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_PleaseChoose {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reason for the order 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Reason {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose a reason 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReasonWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReasonWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Refund 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_RefundAmount {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_RefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card refund 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_RefundOfCreditCardOnce {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_RefundOfCreditCardOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund method 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_RefundType {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_RefundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATM transfer 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_Remittance {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_Remittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose at least one item to return 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_RequiredWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_RequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return description 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnDescription {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please write your return description in less than 200 words 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnDescriptionPrompt {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please fill in the return description 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnDescriptionWarning {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnDescriptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnGoods {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If an order matches a promotion, you have to return everything in it, including gifts 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnMsgAllOrders {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnMsgAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Once the return is requested, we will contact you 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnMsgContact {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnMsgContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Once returned, coupons used on these items will not be returned to you 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnMsgCoupon {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnMsgCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I hereby request a return and allow 91APP to handle the receipt of this order (For example: invoice or sales allowances) 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnMsgInvoice {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnMsgInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The items you purchased match a promotion, you have to return them togetherPlease contact customer service if you have any questions 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnMsgService {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnMsgService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to my orders 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_ReturnOrderSearch {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_ReturnOrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose area 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_SelectDistrict {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_SelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check the items you want to return 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_SelectProduct {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid format 的當地語系化字串。
        /// </summary>
        public static string Pages_ReturnGoodsRequest_WrongFormat {
            get {
                return ResourceManager.GetString("Pages_ReturnGoodsRequest_WrongFormat", resourceCulture);
            }
        }
    }
}
