//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Base {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Base() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.Base", typeof(Base).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Account {
            get {
                return ResourceManager.GetString("Pages_Base_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Address {
            get {
                return ResourceManager.GetString("Pages_Base_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add to Cart 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_AddShoppingCart {
            get {
                return ResourceManager.GetString("Pages_Base_AddShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully added 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_AddSuccess {
            get {
                return ResourceManager.GetString("Pages_Base_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Cancel {
            get {
                return ResourceManager.GetString("Pages_Base_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Category {
            get {
                return ResourceManager.GetString("Pages_Base_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_CategoryAll {
            get {
                return ResourceManager.GetString("Pages_Base_CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Popular items 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_CategoryAlls {
            get {
                return ResourceManager.GetString("Pages_Base_CategoryAlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Check {
            get {
                return ResourceManager.GetString("Pages_Base_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please make sure your information is correct 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_CheckFields {
            get {
                return ResourceManager.GetString("Pages_Base_CheckFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wishlist 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Collect {
            get {
                return ResourceManager.GetString("Pages_Base_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address Book 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_CommonAddressee {
            get {
                return ResourceManager.GetString("Pages_Base_CommonAddressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Count {
            get {
                return ResourceManager.GetString("Pages_Base_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Delete {
            get {
                return ResourceManager.GetString("Pages_Base_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Description {
            get {
                return ResourceManager.GetString("Pages_Base_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Ecoupon {
            get {
                return ResourceManager.GetString("Pages_Base_Ecoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Editor {
            get {
                return ResourceManager.GetString("Pages_Base_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon not applicable 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ExcludeEcoupon {
            get {
                return ResourceManager.GetString("Pages_Base_ExcludeEcoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to connect, please check your internet connection 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FailedToConnect {
            get {
                return ResourceManager.GetString("Pages_Base_FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Facebook post 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FbPost {
            get {
                return ResourceManager.GetString("Pages_Base_FbPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First Name 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FirstName {
            get {
                return ResourceManager.GetString("Pages_Base_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First name is required 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FirstNameRequired {
            get {
                return ResourceManager.GetString("Pages_Base_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping fee 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Freight {
            get {
                return ResourceManager.GetString("Pages_Base_Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gift with purchase discount 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FullDiscount {
            get {
                return ResourceManager.GetString("Pages_Base_FullDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chinese full name 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_FullName {
            get {
                return ResourceManager.GetString("Pages_Base_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gifts 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Gifts {
            get {
                return ResourceManager.GetString("Pages_Base_Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No gifts left 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_GiftsFinish {
            get {
                return ResourceManager.GetString("Pages_Base_GiftsFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Index {
            get {
                return ResourceManager.GetString("Pages_Base_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Name 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_LastName {
            get {
                return ResourceManager.GetString("Pages_Base_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last name is required 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_LastNameRequired {
            get {
                return ResourceManager.GetString("Pages_Base_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must be less than 50 characters 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_MaxNameLength {
            get {
                return ResourceManager.GetString("Pages_Base_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mobile phone 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Mobile {
            get {
                return ResourceManager.GetString("Pages_Base_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mobile number is required 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_MobileRequired {
            get {
                return ResourceManager.GetString("Pages_Base_MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment method 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ModePay {
            get {
                return ResourceManager.GetString("Pages_Base_ModePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping method 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ModeTransport {
            get {
                return ResourceManager.GetString("Pages_Base_ModeTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully modified 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ModifySuccess {
            get {
                return ResourceManager.GetString("Pages_Base_ModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More categories 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_MoreCategory {
            get {
                return ResourceManager.GetString("Pages_Base_MoreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_NextStep {
            get {
                return ResourceManager.GetString("Pages_Base_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No default address available 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_NoRecipient {
            get {
                return ResourceManager.GetString("Pages_Base_NoRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not yet on sale 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_NotYetOpenSale {
            get {
                return ResourceManager.GetString("Pages_Base_NotYetOpenSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Ok {
            get {
                return ResourceManager.GetString("Pages_Base_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose any discount 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_OptionalOffers {
            get {
                return ResourceManager.GetString("Pages_Base_OptionalOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel Orders 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_OrderCancel {
            get {
                return ResourceManager.GetString("Pages_Base_OrderCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order details 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_OrderList {
            get {
                return ResourceManager.GetString("Pages_Base_OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Orders 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_OrderSearch {
            get {
                return ResourceManager.GetString("Pages_Base_OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original price 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_OriginalPrice {
            get {
                return ResourceManager.GetString("Pages_Base_OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checkout 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_PayImmediately {
            get {
                return ResourceManager.GetString("Pages_Base_PayImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_PhoneNumber {
            get {
                return ResourceManager.GetString("Pages_Base_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Important notice 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Precautions {
            get {
                return ResourceManager.GetString("Pages_Base_Precautions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Information 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ProductInformation {
            get {
                return ResourceManager.GetString("Pages_Base_ProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item number 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ProductNumber {
            get {
                return ResourceManager.GetString("Pages_Base_ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipient 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Recipient {
            get {
                return ResourceManager.GetString("Pages_Base_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_RecipientAddress {
            get {
                return ResourceManager.GetString("Pages_Base_RecipientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recommended 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_RecommendProduct {
            get {
                return ResourceManager.GetString("Pages_Base_RecommendProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund information 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_RefundInformation {
            get {
                return ResourceManager.GetString("Pages_Base_RefundInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notes 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Remark {
            get {
                return ResourceManager.GetString("Pages_Base_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required column 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Required {
            get {
                return ResourceManager.GetString("Pages_Base_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to Home 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ReturnHomePage {
            get {
                return ResourceManager.GetString("Pages_Base_ReturnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Previous page 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ReturnPage {
            get {
                return ResourceManager.GetString("Pages_Base_ReturnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return to shopping cart 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ReturnShoppingCart {
            get {
                return ResourceManager.GetString("Pages_Base_ReturnShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Save {
            get {
                return ResourceManager.GetString("Pages_Base_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose city/county 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_SelectCounty {
            get {
                return ResourceManager.GetString("Pages_Base_SelectCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Share 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Share {
            get {
                return ResourceManager.GetString("Pages_Base_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shop name 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ShopName {
            get {
                return ResourceManager.GetString("Pages_Base_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_ShoppingCartNumber {
            get {
                return ResourceManager.GetString("Pages_Base_ShoppingCartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coming Soon 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_SoldOutting {
            get {
                return ResourceManager.GetString("Pages_Base_SoldOutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Submit {
            get {
                return ResourceManager.GetString("Pages_Base_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_TotalAmount {
            get {
                return ResourceManager.GetString("Pages_Base_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unified Business Number 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_UniformNumbers {
            get {
                return ResourceManager.GetString("Pages_Base_UniformNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        public static string Pages_Base_Update {
            get {
                return ResourceManager.GetString("Pages_Base_Update", resourceCulture);
            }
        }
    }
}
