//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.VipMember {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.VipMember.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Total (discounts included) 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_Amount {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Spend another {0} dollars before{1} to retain your {2} status 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_AsLongAsConsumption {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_AsLongAsConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address Book 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_CommonAddressee {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_CommonAddressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FAQ 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_CommonProblem {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_CommonProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_CommonProblemDescription {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_CommonProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Used Unified Business Number 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_CommonUniformNumbers {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_CommonUniformNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Congratulations, you are already the highest tier 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_Congratulations {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extension conditions 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_ContinuedConditions {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_ContinuedConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total purchase amount 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_CumulativeConsumptionAmount {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_CumulativeConsumptionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reach {0} dollars to upgrade your tier 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_EnoughDollar {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_EnoughDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} expired 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_Expire {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last update 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_LastUpdate {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last update time 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_LastUpdateTime {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member birthday gift 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberBirthDayPresent {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberBirthDayPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member points/special gifts 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberCollectPoint {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberCollectPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member information is being updated 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberDataUpdate {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberDataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Membership 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberEntrance {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Membership tiers 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberLevelDescription {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Membership activation gift 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberOpenCardGifts {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberOpenCardGifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Terms of Service &amp; Privacy Policy 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberPrivacyDescription {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberPrivacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personal Information 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberProfile {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 General settings 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberSetting {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Membership system data is being updated, please refresh the page later 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MemberSystemUpdate {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MemberSystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Password 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_ModifyPassWord {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_ModifyPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Wishlist 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MyCollect {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_MyEcoupon {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_MyEcoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} dollars short 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_NotEnoughDollar {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_NotEnoughDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order date 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderDate {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More Orders 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderMorePreivew {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderMorePreivew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More Orders 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderMorePreview {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderMorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No orders yet 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderNotFound {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order No. 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderNumber {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recent orders 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderRecord {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Details 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrdersContent {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrdersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Order 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderSearch {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order status 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OrderStatus {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Other features 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_OtherFeatures {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_OtherFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permanently effective 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_PermanentValidity {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_PermanentValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please search again tomorrow 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_PleaseCheckAgainTomorrow {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_PleaseCheckAgainTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System data is being updated, please try again later 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_SystemUpdate {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_SystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total purchase for the day 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_TheSameDayConsumption {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_TheSameDayConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search orders from other platforms 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_ThirdParty {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total purchase 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_TotalPurchase {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_TotalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incomplete 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_Undone {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_Undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tiers 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_UpgradedLevel {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_UpgradedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hello, welcome 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberIndex_Welcome {
            get {
                return ResourceManager.GetString("Pages_VipMemberIndex_Welcome", resourceCulture);
            }
        }
    }
}
