//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.VipMember {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.VipMember.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 I have read and agree to the&lt;a href=&quot;/V2/VipMember/AgreePrivacy&quot;&gt; Membership Policy&lt;/a&gt; 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_AgreedMemberStatementofInterest {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_AgreedMemberStatementofInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check &quot;I have read and agree to the Membership Policy&quot; 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_AgreedMemberStatementofInterestCheck {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_AgreedMemberStatementofInterestCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Annual income 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_AnnualIncome {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_AnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Birthday 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Birthday {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to change your birthday? You can receive only one birthday gift per year 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_CanOnlyReceiveBirthdayGift {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_CanOnlyReceiveBirthdayGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Have children 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Children {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Completed {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Educational attainment 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_EducationLevel {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Email {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Error {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Female 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Female {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_FieldRequired {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gender 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Gender {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Family status 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_HasChildren {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_HasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID number 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_IDCardNumber {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_IDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill in member information right away, and you might win special offers 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_ImmediatelyWrite {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_ImmediatelyWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your email, for example: new@91app.com 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_InputEmail {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your Taiwanese ID number, for example: A123456789 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_InputIDCardNumber {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_InputIDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your landline number, for example: 0771234568 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_InputLocalCalls {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_InputLocalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Landline 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_LocalCalls {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_LocalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Male 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Male {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Marriage 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Marital {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Marital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Married 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Married {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have finished writing your member information! 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberCompleted {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have finished writing your member information and won an activation gift, congratulations 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberCompletedOpenCard {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberCompletedOpenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member information saved 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberCompletedSave {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberCompletedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have synced your store member information 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberSync {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have synced your store member information and won an activation gift, congratulations 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberSyncOpenCard {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberSyncOpenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill in member information 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_MemberWrite {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_MemberWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Name {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name must be more than two words 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_NameLimitMsg {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_NameLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Single 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_NnMarried {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_NnMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No children 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_NoChildren {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_NoChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_PassWord {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please leave a Taiwan mobile number, for exmaple: 0912345678 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_PhoneMsg {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_PhoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Occupation 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_Profession {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incorrect informationPlease check your information 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_TheDataEnteredIsIncorrect {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_TheDataEnteredIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 or fill in the following information 的當地語系化字串。
        /// </summary>
        public static string Pages_VipMemberProfile_WriteFollowInformation {
            get {
                return ResourceManager.GetString("Pages_VipMemberProfile_WriteFollowInformation", resourceCulture);
            }
        }
    }
}
