//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.ECoupon {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyECoupon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyECoupon() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.ECoupon.MyECoupon", typeof(MyECoupon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon area 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_CouponArea {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_CouponArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon promotion 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_CouponPromotion {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_CouponPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupons will be removed in the following situations 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_CouponsWillBeRemoved {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_CouponsWillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {{0}} dollars worth 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_DollarsWorth {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_DollarsWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Expired coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_ExpiredCoupons {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_ExpiredCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gentle reminder 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_GentleReminder {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_GentleReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to shop home 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_GoToShopHome {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_GoToShopHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List of coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_ListOfCoupons {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_ListOfCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_MyCoupons {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_MyCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No coupons at the moment 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_NoCouponsMoment {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_NoCouponsMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter coupon code 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_PleaseEnterCouponCode {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_PleaseEnterCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have not yet received any coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_ReceivedAnyCoupons {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_ReceivedAnyCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Used coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_UsedCoupons {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_UsedCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I want to enter coupon code 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_WantToEnterCouponCode {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_WantToEnterCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Will expire soon 的當地語系化字串。
        /// </summary>
        public static string Pages_Ecoupon_WillExpireSoon {
            get {
                return ResourceManager.GetString("Pages_Ecoupon_WillExpireSoon", resourceCulture);
            }
        }
    }
}
