//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TradesOrderList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TradesOrderList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder.TradesOrderList", typeof(TradesOrderList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer account 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_Amount {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount to pay 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_AmountToPay {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATM payment information 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_ATM {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the transfer account and amount through an online bank, any [網路ATM] or [ATM自動提款機] from a bank or post office to complete your payment. 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_ATMDeadlineMsg {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_ATMDeadlineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This payment account will become invalid when it expires. You will have to purchase it again. 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_ATMMsg {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_ATMMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATM payment information 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_ATMPayInfo {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_ATMPayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer bank 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_Bank {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment deadline 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderList_PaymentDeadline {
            get {
                return ResourceManager.GetString("Page_TradesOrderList_PaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exchange request 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_ApplyChange {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_ApplyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Request a return 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_ApplyReturn {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_ApplyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If some of the items are cancelled, the store will let you know what&apos;s the correct amount to pay 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_CancelMessage {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please confirm your refund account information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_ConfirmAccount {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your shipping fee 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_Fee {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Including shipping 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_IncludesFee {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_IncludesFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order not found 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_NoData {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your order 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_Order {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order date 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_OrderDate {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pickup form 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_PickUp {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please tell us the refund account information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_ProvideAccount {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_ProvideAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund failed 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_RefundFailed {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_RefundFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Awaiting refund 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_WaitingRefund {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_WaitingRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your &lt;label class=&quot;info&quot;&gt;winning invoice &lt;/label&gt; is pending, please tell us your recipient information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderList_WinningInvoice {
            get {
                return ResourceManager.GetString("Pages_TradesOrderList_WinningInvoice", resourceCulture);
            }
        }
    }
}
