//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TradesOrderRefundInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TradesOrderRefundInfo() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder.TradesOrderRefundInfo", typeof(TradesOrderRefundInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your account 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderRefundInfo_EnterAccount {
            get {
                return ResourceManager.GetString("Page_TradesOrderRefundInfo_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_AccountNo {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The length is {0} characters, you have entered {1} characters, only numbers allowed 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_AccountNoMsgVerifi {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_AccountNoMsgVerifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter the correct account 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_AccountNoWarning {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_AccountNoWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankAccountOwner {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankAccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter account name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankAccountOwnerWarning {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankAccountOwnerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bank name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankName {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose bank name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankNameWarning {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankSubName {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_BankSubNameWarning {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_BankSubNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please confirm your refund account information, and fill in the following information so we can give you your refund 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_ConfirmMessage {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_Coupon {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card bank 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_CreditCardBankName {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_CreditCardBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter account name 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_EnterBankAccountOwner {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_EnterBankAccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter code or keyword 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_EnterKeyWord {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_EnterKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order status 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_OrderStatus {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_PleaseChoose {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_Price {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Promotional discount 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_PromotionDiscount {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_PromotionDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund amount 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundAmount {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund account information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundBankAccount {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping refund content 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundFee {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundInfo {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund order content 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundOrderInfo {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund method 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RefundType {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RefundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incomplete refund account information, please fill in the following information so we can give you your refund 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_RequiredMessage {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item temperature 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_TemperatureType {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_TemperatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping cart number 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_TgId {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_TgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount paid 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_TotalPayment {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund information updated 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_UpdateMessage {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid format 的當地語系化字串。
        /// </summary>
        public static string Pages_TradesOrderRefundInfo_WrongFormat {
            get {
                return ResourceManager.GetString("Pages_TradesOrderRefundInfo_WrongFormat", resourceCulture);
            }
        }
    }
}
