//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TradesOrderDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TradesOrderDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.TradesOrder.TradesOrderDetail", typeof(TradesOrderDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer account 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderDetail_Account {
            get {
                return ResourceManager.GetString("Page_TradesOrderDetail_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount to pay 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderDetail_AmountToPay {
            get {
                return ResourceManager.GetString("Page_TradesOrderDetail_AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This payment account will become invalid when it expires. You will have to purchase it again. 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderDetail_ATMMsg {
            get {
                return ResourceManager.GetString("Page_TradesOrderDetail_ATMMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer bank 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderDetail_Bank {
            get {
                return ResourceManager.GetString("Page_TradesOrderDetail_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment deadline 的當地語系化字串。
        /// </summary>
        public static string Page_TradesOrderDetail_PaymentDeadline {
            get {
                return ResourceManager.GetString("Page_TradesOrderDetail_PaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delivery address 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Address {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exchange request 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ApplyChange {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ApplyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Request a return 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ApplyReturn {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ApplyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coupon discount 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_CouponDiscount {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_CouponDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delivery method 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_DeliveryMethod {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Detail {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discounted 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Discount {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send it to me early 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_EarlySend {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_EarlySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change recipient information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_EditDelivery {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_EditDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Estimated to ship on {0} 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ExpectedDelivery {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ExpectedDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping fee {0} dollars 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Fee {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Invoice {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice status 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_InvoiceStatus {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Map {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notes 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Memo {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill in /modify recipient information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ModifiedDelivery {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ModifiedDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order notes 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_OrderMemo {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_OrderMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order snapshot 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_OrderSnapshot {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_OrderSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order status 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_OrderStatus {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount paid 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Payment {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Payment_x0008_Info {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Payment_x0008_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment total 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_PaymentValue {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_PaymentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact number 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Phone {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Already picked up 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Pickedup {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Pickedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pickup form 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_PickUp {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Price {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Promotional discount 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_PromotionDiscount {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_PromotionDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Promotional discount amount 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_PromotionDiscountAmount {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_PromotionDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipient 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Recipient {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund failed, please   &lt;a class=&quot;text status-text&quot; ng-href=&quot;{0}&quot;&gt;click here&lt;/a&gt; to rewrite transfer information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_RefundFailedMessage {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_RefundFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not yet available, please &lt;a class=&quot;text status-text&quot; ng-href=&quot;{0}&quot;&gt; click here &lt;/a&gt; to fill in 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_RefundInfoMeassage {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_RefundInfoMeassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return and exchange instructions 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ReturnChangeDescription {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ReturnChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Send {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delivery information 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_ShippingInfo {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_ShippingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Won 的當地語系化字串。
        /// </summary>
        public static string Pages_TradeOrderDetail_Winning {
            get {
                return ResourceManager.GetString("Pages_TradeOrderDetail_Winning", resourceCulture);
            }
        }
    }
}
