//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.Question {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerServiceCenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerServiceCenter() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.Question.CustomerServiceCenter", typeof(CustomerServiceCenter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Ask 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_AskQuestion {
            get {
                return ResourceManager.GetString("Pages_Question_AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We are sorry! If you didn&apos;t choose to donate your invoice when you make your purchase, you can&apos;t change it now 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CanInvoiceGiftMsg {
            get {
                return ResourceManager.GetString("Pages_Question_CanInvoiceGiftMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ Can I donate my invoice? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CanInvoiceGiftTitle {
            get {
                return ResourceManager.GetString("Pages_Question_CanInvoiceGiftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Press Return Member Carrier, and you will be redirected to the E-invoice Platform for the return 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ClickMembersHouseholdsMsg {
            get {
                return ResourceManager.GetString("Pages_Question_ClickMembersHouseholdsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FAQ 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CommonProblem {
            get {
                return ResourceManager.GetString("Pages_Question_CommonProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Once returned, you can immediately search all invoices of this membership card on the E-invoice Platform. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CompliteMembersHouseholdsMsg {
            get {
                return ResourceManager.GetString("Pages_Question_CompliteMembersHouseholdsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details of returned e-invoices can still be searched on our website 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CompliteMembersHouseholdsMsgOne {
            get {
                return ResourceManager.GetString("Pages_Question_CompliteMembersHouseholdsMsgOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer service 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CustomerService {
            get {
                return ResourceManager.GetString("Pages_Question_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer service message 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CustomerServiceMessage {
            get {
                return ResourceManager.GetString("Pages_Question_CustomerServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We are sorry! The invoice for your order is printed by the system automatically. The name and price of the item will stay the way it is, so please understand that you can&apos;t choose the date, change the name or price. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_DateOpeningMsg {
            get {
                return ResourceManager.GetString("Pages_Question_DateOpeningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ Can I choose the issue date of the invoice, change the name of the item or its price? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_DateOpeningTitle {
            get {
                return ResourceManager.GetString("Pages_Question_DateOpeningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to &quot;My Account&gt;My Coupons&quot; to search coupons or enter coupon codes. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponMsg {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponNotes {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 8. Coupons are compatible with other discounts in the shop. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleEight {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5. When an order is cancelled or returned, the coupons used on it will become invalid and will not be returned to you. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleFive {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 4. Coupons can be used only once and should not be used as cash, once used they cannot be restored. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleFour {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1. Only one couple allowed for each shop, each time you check out. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleOne {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7. Coupons can&apos;t be used on shipping. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleSeven {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 6. Coupons expire, and when they do they can no longer be used or restored. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleSix {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3. If an item is marked as &quot;Coupons not applicable,&quot; you can&apos;t use coupons on it. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleThree {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   Rules for using coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleTitle {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2. No more than 30% discount of total purchase amount is allowed. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponRuleTow {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponRuleTow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   My Coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponTitle {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When you&apos;re checking out, click use coupons or enter coupon codes to get discounts! 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponUseMsg {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponUseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   How to use coupons 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ECouponUseTitle {
            get {
                return ResourceManager.GetString("Pages_Question_ECouponUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E-invoice instructions 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ElectronicInvoiceDescription {
            get {
                return ResourceManager.GetString("Pages_Question_ElectronicInvoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Free Financial Data Center 24h service number 0800-52-1988 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ElectronicInvoicePhone {
            get {
                return ResourceManager.GetString("Pages_Question_ElectronicInvoicePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E-invoice Platform, Ministry of Finance 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ElectronicInvoicePlatform {
            get {
                return ResourceManager.GetString("Pages_Question_ElectronicInvoicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return E-invoice 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ElectronicInvoicesHouseholds {
            get {
                return ResourceManager.GetString("Pages_Question_ElectronicInvoicesHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If you want the E-invoice certificate please go to &quot;Order search&gt;Click the order details&gt;Invoice,&quot;read the E-invoice instructions and write your recipient information. The customer service will work on it right away.Reminder: After you have picked up your item you can go to &quot;Order sear&gt;Click the order details&gt;Invoice&quot; to search your E-invoice. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_GetElectronicInvoiceMsg {
            get {
                return ResourceManager.GetString("Pages_Question_GetElectronicInvoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ How do I get physical invoices? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_GetElectronicInvoiceTitle {
            get {
                return ResourceManager.GetString("Pages_Question_GetElectronicInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return search 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HomeInquiry {
            get {
                return ResourceManager.GetString("Pages_Question_HomeInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Winning invoices that are returned will be notified by the Financial Data Center, not by us. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HomeInquiryMsg {
            get {
                return ResourceManager.GetString("Pages_Question_HomeInquiryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On the 25th of every odd-numbered month, the E-invoice platform, Ministry of Finance will do all the checking, and on the 28th, when we receive the winning numbers from them, the information will be shown on the Order search page, Invoice. Notification method will depend on invoice carrier type and carrier returning status, as follows: 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowInvoiceAwardMsgOne {
            get {
                return ResourceManager.GetString("Pages_Question_HowInvoiceAwardMsgOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Member CarrierInvoice carrier has been returned: Winning numbers will be announced on the E-invoice Platform, Ministry of Finance. ///Invoice carrier not yet returned: Winners will be informed by us after the E-invoice Platform, Ministry of Finance has announced the winning numbers on the 28th of every odd numbered month. We will ask for your address through email and text message, then send the winning invoice to you by mail. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowInvoiceAwardMsgThree {
            get {
                return ResourceManager.GetString("Pages_Question_HowInvoiceAwardMsgThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Using “Mobile barcode carrier” or “Natural person credential carrier,” the winning invoices will be notified by the E-invoice Platform, Ministry of Finance, to receive the prize.  的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowInvoiceAwardMsgTwo {
            get {
                return ResourceManager.GetString("Pages_Question_HowInvoiceAwardMsgTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ How do I know whether or not my invoice has won? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowInvoiceAwardTitle {
            get {
                return ResourceManager.GetString("Pages_Question_HowInvoiceAwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An invoice is issued right after the payment is made and item is shipped. You can go to “Order search&gt;Click the order details you want&gt;Invoice” anytime to search for your invoice number. If you chose to donate the invoice when you made your order, the last 3 digits of the donated invoice number will be displayed in asterix(*) to protect the rights and interests of the recipient. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowUniformNumbersMsg {
            get {
                return ResourceManager.GetString("Pages_Question_HowUniformNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ How do I know the invoice number? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_HowUniformNumbersTitle {
            get {
                return ResourceManager.GetString("Pages_Question_HowUniformNumbersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return Member carrier 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_MembersHouseholds {
            get {
                return ResourceManager.GetString("Pages_Question_MembersHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 According to Decree No. 1020002795, the Implementation Guidelines of E-invoices, issued by the Ministry of Finance, effective since January 1, 2014, E-invoices issued by our website do not come in physical form so we won&apos;t send you any. We do upload the E-invoices to the E-invoice Platform, Ministry of Finance within a certain period of time. You can go to Member area&gt;Customer service/FAQ&gt;E-invoice return to have it returned to your carrier. Winning invoices that are returned will be notified by the E-invoi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_NotElectronicInvoiceMsg {
            get {
                return ResourceManager.GetString("Pages_Question_NotElectronicInvoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ Why didn&apos;t I receive my invoice? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_NotElectronicInvoiceTitle {
            get {
                return ResourceManager.GetString("Pages_Question_NotElectronicInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 According to Decree No. 1020002795, the Implementation Guidelines of E-invoices, issued by the Ministry of Finance, we don&apos;t proactively send invoices to our customers, but we have to upload them to the integrated service platform within a certain period of time, so you can still search your purchase history on the E-invoice Platform, Ministry of Finance. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_NotInvoiceAwardMsg {
            get {
                return ResourceManager.GetString("Pages_Question_NotInvoiceAwardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ Will I get the invoices back if they didn&apos;t win? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_NotInvoiceAwardTitle {
            get {
                return ResourceManager.GetString("Pages_Question_NotInvoiceAwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You don&apos;t have anything in your question history 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_NotQuestionRecords {
            get {
                return ResourceManager.GetString("Pages_Question_NotQuestionRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Before an item is shipped, you can go to &quot;My Account&gt;Order Search&quot; and click &quot;Cancel Order.&quot; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderCancelMsg {
            get {
                return ResourceManager.GetString("Pages_Question_OrderCancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   How do I cancel an order 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderCancelTitle {
            get {
                return ResourceManager.GetString("Pages_Question_OrderCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderNumber {
            get {
                return ResourceManager.GetString("Pages_Question_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order NO. / Item NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderNumberOrProductNumber {
            get {
                return ResourceManager.GetString("Pages_Question_OrderNumberOrProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order progress 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderProgress {
            get {
                return ResourceManager.GetString("Pages_Question_OrderProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can search the delivery progress of an item in &quot;My Account&gt;Order Search.&quot; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderProgressMsg {
            get {
                return ResourceManager.GetString("Pages_Question_OrderProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   How do I track the order progress 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderProgressTitle {
            get {
                return ResourceManager.GetString("Pages_Question_OrderProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When an order is made, the system will send you an Order Confirmation email to confirm the information of the order, including its details and recipient information. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderSuccessMsg {
            get {
                return ResourceManager.GetString("Pages_Question_OrderSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   Is the order successful 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderSuccessTitle {
            get {
                return ResourceManager.GetString("Pages_Question_OrderSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ProductNumber {
            get {
                return ResourceManager.GetString("Pages_Question_ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question type 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionCategory {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question content 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionContent {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionNumber {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To whom are you asking 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionObject {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Below is your question history with customer service 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionRecords {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSend {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Once the question is sent, the shop will reply.  的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSendAfter {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSendAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSingleNumber {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSingleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card: if you used credit card to pay, we will return the payment to the account of the credit card you used to pay. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_RefundCreditCardMsg {
            get {
                return ResourceManager.GetString("Pages_Question_RefundCreditCardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   Refund: The refund method will be the same as your payment method 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_RefundInstructionsTitle {
            get {
                return ResourceManager.GetString("Pages_Question_RefundInstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convenience store/supermarket pickup payment: If you used the convenience store/supermarket pickup payment, please write the correct refund account information on your return request according to the return/refund page. Once the shop has confirmed the return, we will give you your refund to your account within 7 business days. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_RefundSuperPickupMsg {
            get {
                return ResourceManager.GetString("Pages_Question_RefundSuperPickupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return/exchange/refund instructions 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ReturnsOrRefundInstructions {
            get {
                return ResourceManager.GetString("Pages_Question_ReturnsOrRefundInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please read &quot;Shopping instructions&gt;Return/exchange instructions.&quot; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ReturnsProductMsg {
            get {
                return ResourceManager.GetString("Pages_Question_ReturnsProductMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎   Return/exchange instructions 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ReturnsProductTitle {
            get {
                return ResourceManager.GetString("Pages_Question_ReturnsProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 According to Article 20 of Decree No. 1020002795, the Implementation Guidelines of E-invoices, that once every two months, the E-invoice Platform, Ministry of Finance should reveal the details of the invoice to organization the buyer chose to donate to before the winning numbers are announced, and notify them of the prizes if they have won. Also, according to the law, you can’t ask for physical copies of donated invoices or change whom you donate to. If you request a return or exchange, we will treat the in [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_SentElectronicInvoiceMsg {
            get {
                return ResourceManager.GetString("Pages_Question_SentElectronicInvoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ What do you do with donated invoices? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_SentElectronicInvoiceTitle {
            get {
                return ResourceManager.GetString("Pages_Question_SentElectronicInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reminder 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_SmallReminder {
            get {
                return ResourceManager.GetString("Pages_Question_SmallReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If you have not yet received the physical invoice, please go to “Order search&gt;Click the order details you want&gt;Invoice” to find the order, click it and tell customer service your need, we will work on it right away. *Invoices with Unified Business No./titles will be sent to you within 10 days after shipping, the send date will then show up on the order search page. If you have received the physical invoice or that it has already been sent, please fill in the debit note on the back of the invoice with the ti [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_UniformNumbersMsg {
            get {
                return ResourceManager.GetString("Pages_Question_UniformNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 What to do when I want to add Unified Business No. for my invoice, or when there is a typo in the Unified Business No./title? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_UniformNumbersTitle {
            get {
                return ResourceManager.GetString("Pages_Question_UniformNumbersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_Welcome {
            get {
                return ResourceManager.GetString("Pages_Question_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On the 25th of every odd-numbered month, the E-invoice platform, Ministry of Finance will do all the checking, and on the 28th, when we receive the winning numbers from them, the information will be shown on the Order search page, Invoice.  的當地語系化字串。
        /// </summary>
        public static string Pages_Question_WhenInvoiceAwardMsg {
            get {
                return ResourceManager.GetString("Pages_Question_WhenInvoiceAwardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ When will you check my invoice to see if I have won? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_WhenInvoiceAwardTitle {
            get {
                return ResourceManager.GetString("Pages_Question_WhenInvoiceAwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice with Unified Business No./title will be sent 10 days after the item was shipped. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_WriteElectronicInvoiceMsg {
            get {
                return ResourceManager.GetString("Pages_Question_WriteElectronicInvoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ◎ Can I get the invoice with Unified Business No./title? When do I get it? 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_WriteElectronicInvoiceTitle {
            get {
                return ResourceManager.GetString("Pages_Question_WriteElectronicInvoiceTitle", resourceCulture);
            }
        }
    }
}
