//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.Question {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionInsert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionInsert() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.Question.QuestionInsert", typeof(QuestionInsert).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Ask 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_AskQuestion {
            get {
                return ResourceManager.GetString("Pages_Question_AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer service message 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_CustomerServiceMessage {
            get {
                return ResourceManager.GetString("Pages_Question_CustomerServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderNumber {
            get {
                return ResourceManager.GetString("Pages_Question_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order NO. / Item NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_OrderNumberOrProductNumber {
            get {
                return ResourceManager.GetString("Pages_Question_OrderNumberOrProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_ProductNumber {
            get {
                return ResourceManager.GetString("Pages_Question_ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question type 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionCategory {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question content 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionContent {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionNumber {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To whom are you asking 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionObject {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSend {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Once the question is sent, the shop will reply.  的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSendAfter {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSendAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Question NO. 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_QuestionSingleNumber {
            get {
                return ResourceManager.GetString("Pages_Question_QuestionSingleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You 的當地語系化字串。
        /// </summary>
        public static string Pages_Question_You {
            get {
                return ResourceManager.GetString("Pages_Question_You", resourceCulture);
            }
        }
    }
}
