//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.CancelGoodsRequest {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class List {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.CancelGoodsRequest.List", typeof(List).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account No. 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_AccountNo {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The length is {0} characters, you have entered {1} characters, only numbers allowed 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_AccountNoMsgVerifi {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_AccountNoMsgVerifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter the correct account 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_AccountNoWarning {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_AccountNoWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your cancellation has been requested 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_Applied {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 So the use of ATM payment transactions, can not be a single cancellation, once checked, will cancel the purchase of all goods. If a gift is given, it must be canceled together. 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_ATMCancelMsg {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_ATMCancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to my orders 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_Back {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account Name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankAccountOwner {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankAccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter account name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankAccountOwnerWarning {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankAccountOwnerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bank Name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankName {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please enter bank name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankNameWarning {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankSubName {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This column is required, please choose branch name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_BankSubNameWarning {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_BankSubNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_Cancel {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Orders (including gifts) eligible for promotions must be cancelled entirely 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CancelMsgAllOrder {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CancelMsgAllOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When the order is cancelled, you won&apos;t get the coupons back 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CancelMsgCoupon {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CancelMsgCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped items can&apos;t be cancelled here 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CancelMsgNotCancel {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CancelMsgNotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If you cancel the entire order, your shipping will be refunded as well 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CancelMsgRefundFee {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CancelMsgRefundFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All items you purchased are promotion eligible, so you must cancel them together. Please contact customer service if you have any questions. 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CancelMsgService {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CancelMsgService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card bank 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_CreditCardBankName {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_CreditCardBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter bank name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_Enter {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your account 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_EnterAccount {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter account name 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_EnterAccountOwner {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_EnterAccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter code or keyword 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_EnterKeyWord {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_EnterKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No item to cancel at the moment 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_NoData {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Refund 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_RefundAmount {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_RefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card refund 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_RefundOfCreditCardOnce {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_RefundOfCreditCardOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refund method 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_RefundType {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_RefundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATM transfer 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_Remittance {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_Remittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose at least one item to cancel 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_RequiredWarning {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_RequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check the items you want to cancel 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_SelectProduct {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid format 的當地語系化字串。
        /// </summary>
        public static string Pages_CancelGoodsRequest_WrongFormat {
            get {
                return ResourceManager.GetString("Pages_CancelGoodsRequest_WrongFormat", resourceCulture);
            }
        }
    }
}
