//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.Shared {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Official_BrandAsidebar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Official_BrandAsidebar() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.Shared.Official_BrandAsidebar", typeof(Official_BrandAsidebar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About us 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_AboutUs {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Brand Story 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_BrandStory {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_BrandStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FAQ 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_CommonProblem {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_CommonProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Membership Terms 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_MemberStatement {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_MemberStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy Policy 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About Our Service 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_ServiceDescription {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About Shop 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_ShopIntroduction {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_ShopIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer Service 的當地語系化字串。
        /// </summary>
        public static string Pages_BrandAsidebar_ShoppingDescription {
            get {
                return ResourceManager.GetString("Pages_BrandAsidebar_ShoppingDescription", resourceCulture);
            }
        }
    }
}
