//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.Shared {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageNotFound {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageNotFound() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.Shared.PageNotFound", typeof(PageNotFound).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About Just Buy 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_AboutNineYi {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_AboutNineYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copyright © 2016 91APP, Inc. All rights reserved 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_Copyrights {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer service 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_CustomerService {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 404 page 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_ErrorPage {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The page you&apos;re looking for might be broken or removed 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_FailedPage {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_FailedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Visit somewhere else 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_GoSomewhere {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_GoSomewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry, we can&apos;t find this page 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_NotFoundPage {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_NotFoundPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy policy 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item categories 的當地語系化字串。
        /// </summary>
        public static string Pages_PageNotFound_ProductCategory {
            get {
                return ResourceManager.GetString("Pages_PageNotFound_ProductCategory", resourceCulture);
            }
        }
    }
}
