//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.LocationPickup {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationPickupDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationPickupDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.LocationPickup.LocationPickupDetail", typeof(LocationPickupDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 All stores 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_AllStores {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_AllStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose again 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ChooseAgain {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ChooseAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose area 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ChooseArea {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ChooseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose store 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ChooseStoreMsg {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ChooseStoreMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose store ({0} stores in total) 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ChooseStoreTotalMsg {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ChooseStoreTotalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose the store for your pickup 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ChoosetheStore {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ChoosetheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm store 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ConfirmStore {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ConfirmStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Holidays 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_Holidays {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No results 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_NoResults {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_Open {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search store (please enter shop name) 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_SearchStore {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_SearchStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show only stores that support pickup 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ShowOnlyStoresMsg {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ShowOnlyStoresMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show only stores that support pickup ({0} stores in total) 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_ShowOnlyStoresTotalMsg {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_ShowOnlyStoresTotalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store area search 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_StoreAreaSearch {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_StoreAreaSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store name 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_StoreName {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weekdays 的當地語系化字串。
        /// </summary>
        public static string Pages_LocationPickup_Weekdays {
            get {
                return ResourceManager.GetString("Pages_LocationPickup_Weekdays", resourceCulture);
            }
        }
    }
}
