//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.Login {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.Login.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Once you log in to your account, it will be bound to your mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_BoundleMobileNumber {
            get {
                return ResourceManager.GetString("Pages_Login_BoundleMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Complete 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_Complete {
            get {
                return ResourceManager.GetString("Pages_Login_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please contact customer service 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_ContactCustomerService {
            get {
                return ResourceManager.GetString("Pages_Login_ContactCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create login password 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_CreateloginPassword {
            get {
                return ResourceManager.GetString("Pages_Login_CreateloginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dial in verification 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_DialVerification {
            get {
                return ResourceManager.GetString("Pages_Login_DialVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Facebook service busy!Please try again later! 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_FacebookServiceMsg {
            get {
                return ResourceManager.GetString("Pages_Login_FacebookServiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Facebook mobile number Next 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_FBMobileNumberNext {
            get {
                return ResourceManager.GetString("Pages_Login_FBMobileNumberNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please verify your mobile number if it&apos;s your first time logging in 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_FirstTimeLogin {
            get {
                return ResourceManager.GetString("Pages_Login_FirstTimeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forgot password 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Pages_Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Free signup 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_FreeSignup {
            get {
                return ResourceManager.GetString("Pages_Login_FreeSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You already have an account 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_HaveAccount {
            get {
                return ResourceManager.GetString("Pages_Login_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Having this account means that you agree to our membership terms and privacy policy 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_HavingAccountMsg {
            get {
                return ResourceManager.GetString("Pages_Login_HavingAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid verification code 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_InvalidVerificationCode {
            get {
                return ResourceManager.GetString("Pages_Login_InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Become a member 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_JoinMember {
            get {
                return ResourceManager.GetString("Pages_Login_JoinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter password of 6-20 characters (letters and numbers) 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_LimitNumberEnTip {
            get {
                return ResourceManager.GetString("Pages_Login_LimitNumberEnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter 6-20 characters (letters and numbers) 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_LimitNumberTip {
            get {
                return ResourceManager.GetString("Pages_Login_LimitNumberTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the 4 digit verification code 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_LimitVerificationCode {
            get {
                return ResourceManager.GetString("Pages_Login_LimitVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log in 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_Login {
            get {
                return ResourceManager.GetString("Pages_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log in 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_LoginMember {
            get {
                return ResourceManager.GetString("Pages_Login_LoginMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_MobileNumber {
            get {
                return ResourceManager.GetString("Pages_Login_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your mobile number is your username 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_MobileNumberIsUsername {
            get {
                return ResourceManager.GetString("Pages_Login_MobileNumberIsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter mobile number Next 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_MobileNumberNext {
            get {
                return ResourceManager.GetString("Pages_Login_MobileNumberNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_MobileNumberTip {
            get {
                return ResourceManager.GetString("Pages_Login_MobileNumberTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please leave a Taiwan mobile number, for exmaple: 0912345678 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_MobileNumberTwTip {
            get {
                return ResourceManager.GetString("Pages_Login_MobileNumberTwTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This number already belongs to a member, please confirm your mobile number or log in again 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_NumberAlreadyMsg {
            get {
                return ResourceManager.GetString("Pages_Login_NumberAlreadyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your {0} official website account 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_OfficialWebsiteAccount {
            get {
                return ResourceManager.GetString("Pages_Login_OfficialWebsiteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter original {0} official website password 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_OriginalPassword {
            get {
                return ResourceManager.GetString("Pages_Login_OriginalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_Password {
            get {
                return ResourceManager.GetString("Pages_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Didn&apos;t receive the text message? 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_Patient {
            get {
                return ResourceManager.GetString("Pages_Login_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please have your phone ready 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_PhoneReady {
            get {
                return ResourceManager.GetString("Pages_Login_PhoneReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please be patient 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_PleaseBePatient {
            get {
                return ResourceManager.GetString("Pages_Login_PleaseBePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When you receive the verification text message, please follow the instructions to complete your signup 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_ReceiveVerificationMsg {
            get {
                return ResourceManager.GetString("Pages_Login_ReceiveVerificationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remember me 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_RememberMe {
            get {
                return ResourceManager.GetString("Pages_Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Resend verification code 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_ResendVerificationCode {
            get {
                return ResourceManager.GetString("Pages_Login_ResendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sign up 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_SignupAccount {
            get {
                return ResourceManager.GetString("Pages_Login_SignupAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You signup is almost complete 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_SignupAlmostComplete {
            get {
                return ResourceManager.GetString("Pages_Login_SignupAlmostComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully logged in 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_SuccessLogin {
            get {
                return ResourceManager.GetString("Pages_Login_SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully signed up 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_SuccessSignup {
            get {
                return ResourceManager.GetString("Pages_Login_SuccessSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The call and the system service will be charged by your carrier 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_SystemServiceTip {
            get {
                return ResourceManager.GetString("Pages_Login_SystemServiceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Third Party mobile number Next 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_ThirdPartyMobileNumberNext {
            get {
                return ResourceManager.GetString("Pages_Login_ThirdPartyMobileNumberNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log in 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_Title {
            get {
                return ResourceManager.GetString("Pages_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use dial in verification 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_UseDialMobileVerification {
            get {
                return ResourceManager.GetString("Pages_Login_UseDialMobileVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please use dial in verification 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_UseDialVerification {
            get {
                return ResourceManager.GetString("Pages_Login_UseDialVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In order to give you a better user experience and system security 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_UserExperienceMsg {
            get {
                return ResourceManager.GetString("Pages_Login_UserExperienceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verification code 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_VerificationCode {
            get {
                return ResourceManager.GetString("Pages_Login_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verification code has been sent to your phone 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_VerificationCodeHasBeenSent {
            get {
                return ResourceManager.GetString("Pages_Login_VerificationCodeHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We are going to send the verification code to you via text message 的當地語系化字串。
        /// </summary>
        public static string Pages_Login_VerificationMsg {
            get {
                return ResourceManager.GetString("Pages_Login_VerificationMsg", resourceCulture);
            }
        }
    }
}
