//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMall.SalePage {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexV2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexV2() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMall.SalePage.IndexV2", typeof(IndexV2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Installments from {0} banks are accepted 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_AcceptBank {
            get {
                return ResourceManager.GetString("Pages_SalePage_AcceptBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View all 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_AllRanking {
            get {
                return ResourceManager.GetString("Pages_SalePage_AllRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Already in shopping cart! 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_AlreadyShoppingCart {
            get {
                return ResourceManager.GetString("Pages_SalePage_AlreadyShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App download link has been sent to your phone! 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_AppDownloadPoint {
            get {
                return ResourceManager.GetString("Pages_SalePage_AppDownloadPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App exclusive! Download right away 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_APPSingleSale {
            get {
                return ResourceManager.GetString("Pages_SalePage_APPSingleSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATM payment 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_AtmPayment {
            get {
                return ResourceManager.GetString("Pages_SalePage_AtmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Banks 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_Bank {
            get {
                return ResourceManager.GetString("Pages_SalePage_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The list is generated 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_BuyWord {
            get {
                return ResourceManager.GetString("Pages_SalePage_BuyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_BuyWordSuccess {
            get {
                return ResourceManager.GetString("Pages_SalePage_BuyWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact us 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_CallService {
            get {
                return ResourceManager.GetString("Pages_SalePage_CallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Popular items 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_CategoryProducts {
            get {
                return ResourceManager.GetString("Pages_SalePage_CategoryProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This page is closed, please check out other items 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ChooseOtherProduct {
            get {
                return ResourceManager.GetString("Pages_SalePage_ChooseOtherProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a size / variation 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ChooseStandardSize {
            get {
                return ResourceManager.GetString("Pages_SalePage_ChooseStandardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Closed 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_Close {
            get {
                return ResourceManager.GetString("Pages_SalePage_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_CreditCard {
            get {
                return ResourceManager.GetString("Pages_SalePage_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customized items 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_CustomProduct {
            get {
                return ResourceManager.GetString("Pages_SalePage_CustomProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can also scan the QR code to download 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_DownloadQRCode {
            get {
                return ResourceManager.GetString("Pages_SalePage_DownloadQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Each installment 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_EachPhase {
            get {
                return ResourceManager.GetString("Pages_SalePage_EachPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid mobile number 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ErrorPhoneFomat {
            get {
                return ResourceManager.GetString("Pages_SalePage_ErrorPhoneFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Estimated shipping date: 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ExpectedShipDate {
            get {
                return ResourceManager.GetString("Pages_SalePage_ExpectedShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Family Mart payment upon pickup 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_FamilyPayment {
            get {
                return ResourceManager.GetString("Pages_SalePage_FamilyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 See more 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_FoundMoreProduct {
            get {
                return ResourceManager.GetString("Pages_SalePage_FoundMoreProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send download link to your phone for free 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_FreeSentDownloadPoint {
            get {
                return ResourceManager.GetString("Pages_SalePage_FreeSentDownloadPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_GoTo {
            get {
                return ResourceManager.GetString("Pages_SalePage_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Best sellers 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_HotSaleRanking {
            get {
                return ResourceManager.GetString("Pages_SalePage_HotSaleRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Popular tags 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_HotTags {
            get {
                return ResourceManager.GetString("Pages_SalePage_HotTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter your mobile number and download the official app to have an even better shopping experience 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_InputPhoneDownload {
            get {
                return ResourceManager.GetString("Pages_SalePage_InputPhoneDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LINE 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_LineMessage {
            get {
                return ResourceManager.GetString("Pages_SalePage_LineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Network busy, please try again later 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_NetworkBusy {
            get {
                return ResourceManager.GetString("Pages_SalePage_NetworkBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ( no purchase lists ) 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_NoBuyWord {
            get {
                return ResourceManager.GetString("Pages_SalePage_NoBuyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Who will be the lucky winner of the purchase! 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_NoBuyWordMsg {
            get {
                return ResourceManager.GetString("Pages_SalePage_NoBuyWordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Official app 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_OfficialApp {
            get {
                return ResourceManager.GetString("Pages_SalePage_OfficialApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No longer available 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_OffShelf {
            get {
                return ResourceManager.GetString("Pages_SalePage_OffShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase in app 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_OpenBuyNow {
            get {
                return ResourceManager.GetString("Pages_SalePage_OpenBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original price $ 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_OriginalPrice {
            get {
                return ResourceManager.GetString("Pages_SalePage_OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Installment 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_Phase {
            get {
                return ResourceManager.GetString("Pages_SalePage_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scan QR code to download 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_PhoneDownloadQRCode {
            get {
                return ResourceManager.GetString("Pages_SalePage_PhoneDownloadQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pre-order item 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_PreOrderProduct {
            get {
                return ResourceManager.GetString("Pages_SalePage_PreOrderProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The category of this item 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ProductCategory {
            get {
                return ResourceManager.GetString("Pages_SalePage_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 items 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ProductCount {
            get {
                return ResourceManager.GetString("Pages_SalePage_ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item specification 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ProductSpecifical {
            get {
                return ResourceManager.GetString("Pages_SalePage_ProductSpecifical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Who bought this ? 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_Purchaselist {
            get {
                return ResourceManager.GetString("Pages_SalePage_Purchaselist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We suggest scanning the QR code to download 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_RecommendedQRCode {
            get {
                return ResourceManager.GetString("Pages_SalePage_RecommendedQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sales focus 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SalesFocus {
            get {
                return ResourceManager.GetString("Pages_SalePage_SalesFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search... 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SearchInput {
            get {
                return ResourceManager.GetString("Pages_SalePage_SearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 has been sent to 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SentTo {
            get {
                return ResourceManager.GetString("Pages_SalePage_SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send Message 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ServiceMessage {
            get {
                return ResourceManager.GetString("Pages_SalePage_ServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7-11 payment upon pickup 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SevenElevenPayment {
            get {
                return ResourceManager.GetString("Pages_SalePage_SevenElevenPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Share and purchase 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShareBuyNow {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShareBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I saw this goodie on 91mai Just Buy Mobile Shopping Mall and I&apos;m sharing it with you 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShareyouMsg {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShareyouMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} - RM {1} 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShippingTypeDisplay_Fixed {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShippingTypeDisplay_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} - Free 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShippingTypeDisplay_Free {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShippingTypeDisplay_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} - RM {1} 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShippingTypeDisplay_OverPrice {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShippingTypeDisplay_OverPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Free shipping over RM {0} 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShippingTypeSubDisplay_OverPrice {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShippingTypeSubDisplay_OverPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show details in desktop mode 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ShowComputerDescription {
            get {
                return ResourceManager.GetString("Pages_SalePage_ShowComputerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit card full payment 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SinglePayment {
            get {
                return ResourceManager.GetString("Pages_SalePage_SinglePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sold {0} item(s) 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SoldCount {
            get {
                return ResourceManager.GetString("Pages_SalePage_SoldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sold out, available soon 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SoldOut {
            get {
                return ResourceManager.GetString("Pages_SalePage_SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Special price $ 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_SpecialPrice {
            get {
                return ResourceManager.GetString("Pages_SalePage_SpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Let me tell you something! Check this one out →{0} 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_TellyouMsg {
            get {
                return ResourceManager.GetString("Pages_SalePage_TellyouMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This item is in collaboration with {0} 的當地語系化字串。
        /// </summary>
        public static string Pages_SalePage_ThisProductSale {
            get {
                return ResourceManager.GetString("Pages_SalePage_ThisProductSale", resourceCulture);
            }
        }
    }
}
