//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.Search {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.Search.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Advanced filter 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_AdvancedFilter {
            get {
                return ResourceManager.GetString("Pages_Search_AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear all 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_AllClear {
            get {
                return ResourceManager.GetString("Pages_Search_AllClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Using more general terms 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_CheckForTypos {
            get {
                return ResourceManager.GetString("Pages_Search_CheckForTypos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Display {
            get {
                return ResourceManager.GetString("Pages_Search_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filter 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Filter {
            get {
                return ResourceManager.GetString("Pages_Search_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New arrivals 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_NewProduct {
            get {
                return ResourceManager.GetString("Pages_Search_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We can&apos;t find the item and its information at the moment 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_NotFoundProduct {
            get {
                return ResourceManager.GetString("Pages_Search_NotFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We were unable to find results for &lt;span class=&apos;hight-light-word&apos;&gt; {0} &lt;/span&gt;
        ///Try Something like 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_NotFoundRelativityProduct {
            get {
                return ResourceManager.GetString("Pages_Search_NotFoundRelativityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anything 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_NotLimited {
            get {
                return ResourceManager.GetString("Pages_Search_NotLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original range 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_OriginalRange {
            get {
                return ResourceManager.GetString("Pages_Search_OriginalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Price {
            get {
                return ResourceManager.GetString("Pages_Search_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price range 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_PriceRange {
            get {
                return ResourceManager.GetString("Pages_Search_PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prices in descending order 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_PricesHighToLow {
            get {
                return ResourceManager.GetString("Pages_Search_PricesHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prices in ascending order 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_PricesLowToHigh {
            get {
                return ResourceManager.GetString("Pages_Search_PricesLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} results found 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_RelatedProducts {
            get {
                return ResourceManager.GetString("Pages_Search_RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Similarity 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Relativity {
            get {
                return ResourceManager.GetString("Pages_Search_Relativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sort 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Sort {
            get {
                return ResourceManager.GetString("Pages_Search_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 We suggest that you 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_Suggest {
            get {
                return ResourceManager.GetString("Pages_Search_Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please modify the content your advanced filter, or search again with another term 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_TransferAdvancedFilter {
            get {
                return ResourceManager.GetString("Pages_Search_TransferAdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checking your spelling 的當地語系化字串。
        /// </summary>
        public static string Pages_Search_TryShorteningKeywords {
            get {
                return ResourceManager.GetString("Pages_Search_TryShorteningKeywords", resourceCulture);
            }
        }
    }
}
