//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NineYi.WebStore.Resources.MobileWebMallV2.Pay {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal landing() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NineYi.WebStore.Resources.MobileWebMallV2.Pay.landing", typeof(landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 He who is patient gets what he wants 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_CanGetWhatHeExpects {
            get {
                return ResourceManager.GetString("Pages_Landing_CanGetWhatHeExpects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep waiting 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_ContinueWait {
            get {
                return ResourceManager.GetString("Pages_Landing_ContinueWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Information is being speed processed 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_DataAccelerationProcessing {
            get {
                return ResourceManager.GetString("Pages_Landing_DataAccelerationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Items added to shopping cart are not purchased 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_DoesNotMeanCompletionOfTransaction {
            get {
                return ResourceManager.GetString("Pages_Landing_DoesNotMeanCompletionOfTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please do not refresh 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_DontReload {
            get {
                return ResourceManager.GetString("Pages_Landing_DontReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Franklin 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_Franklin {
            get {
                return ResourceManager.GetString("Pages_Landing_Franklin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Leaving this page will interrupt this purchase, are you sure you want to pick your items again 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_LeavingPageWillInterruptThisOrder {
            get {
                return ResourceManager.GetString("Pages_Landing_LeavingPageWillInterruptThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Page idle overtime, please return to shopping cart and pick your items again 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_PageTimeout {
            get {
                return ResourceManager.GetString("Pages_Landing_PageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please follow the checkout procedure to ensure a successful purchase 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_PleaseFollowTheStepsToCompleteTheCheckoutProcess {
            get {
                return ResourceManager.GetString("Pages_Landing_PleaseFollowTheStepsToCompleteTheCheckoutProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please be patient 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_PleaseWaitWithPatience {
            get {
                return ResourceManager.GetString("Pages_Landing_PleaseWaitWithPatience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping cart is busy, we are working hard on it 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_ShoppingCartHandleTrafficJam {
            get {
                return ResourceManager.GetString("Pages_Landing_ShoppingCartHandleTrafficJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping has been waiting for {0} seconds 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_ShoppingCartHasBeenWaiting {
            get {
                return ResourceManager.GetString("Pages_Landing_ShoppingCartHasBeenWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping cart information is being processed 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_ShoppingCartProcessing {
            get {
                return ResourceManager.GetString("Pages_Landing_ShoppingCartProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping cart is a little busy 的當地語系化字串。
        /// </summary>
        public static string Pages_Landing_ShoppingCartSlightlySmallTrafficJam {
            get {
                return ResourceManager.GetString("Pages_Landing_ShoppingCartSlightlySmallTrafficJam", resourceCulture);
            }
        }
    }
}
